# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AgitatorInRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('data', models.TextField(blank=True, max_length=64000, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_update_time'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registrations_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('timezone_delta', models.IntegerField(help_text='Разница с UTC в секундах, например, для UTC+3 указано +10800')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RegionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='door_to_door_bot.Region')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='agitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.User'),
        ),
        migrations.AddField(
            model_name='agitatorinregion',
            name='agitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.User'),
        ),
        migrations.AddField(
            model_name='agitatorinregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Region'),
        ),
        migrations.AddField(
            model_name='adminrights',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Region'),
        ),
        migrations.AddField(
            model_name='adminrights',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.User'),
        ),
        migrations.AlterUniqueTogether(
            name='agitatorinregion',
            unique_together=set([('agitator', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='adminrights',
            unique_together=set([('user', 'region')]),
        ),
    ]
