# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgitationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('place', models.CharField(max_length=500)),
                ('agitators', models.ManyToManyField(to='door_to_door_bot.User')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlatContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Flat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.AgitationTeam')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('min_flat_number', models.IntegerField(blank=True, null=True)),
                ('max_flat_number', models.IntegerField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.House')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Region')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.Street'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_to_door_bot.HouseBlock'),
        ),
    ]
