# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0002_auto_20171021_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationteam',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
