# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0003_agitationteam_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
