# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0004_auto_20171022_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatcontact',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatcontact',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatcontact',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Нет дома'), (1, 'Позитив'), (2, 'Негатив')], null=True, validators=[djchoices.choices.ChoicesValidator({0: 'Нет дома', 1: 'Позитив', 2: 'Негатив'})]),
        ),
        migrations.AlterField(
            model_name='flatcontact',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='door_to_door_bot.Flat'),
        ),
        migrations.AlterField(
            model_name='flatcontact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='door_to_door_bot.AgitationTeam'),
        ),
        migrations.RemoveField(
            model_name='flatcontact',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='flatcontact',
            unique_together=set([('flat', 'team')]),
        ),
    ]
