# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0005_auto_20171022_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatcontact',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет дома'), (1, 'Позитив'), (2, 'Негатив'), (3, 'Нейтрально')], null=True, validators=[djchoices.choices.ChoicesValidator({0: 'Нет дома', 1: 'Позитив', 2: 'Негатив', 3: 'Нейтрально'})]),
        ),
    ]
