# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0006_auto_20171023_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to='door_to_door_bot.User'),
        ),
    ]
