# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0007_flatcontact_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatcontact',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет дома'), (1, 'Не открыли - отказ'), (2, 'Открыли - отказ'), (3, 'Открыли - сторонник'), (4, 'Агрессия')], null=True, validators=[djchoices.choices.ChoicesValidator({0: 'Нет дома', 1: 'Не открыли - отказ', 2: 'Открыли - отказ', 3: 'Открыли - сторонник', 4: 'Агрессия'})]),
        ),
    ]
