# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_to_door_bot', '0009_auto_20171030_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatcontact',
            name='phone',
        ),
        migrations.AddField(
            model_name='flatcontact',
            name='contacts',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
