# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgitationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AgitationPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Например, «Гражданский пр., 74»', max_length=200)),
                ('geo_latitude', models.FloatField(blank=True, null=True)),
                ('geo_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agitationevent',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.AgitationPlace'),
        ),
    ]
