# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgitationEventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('agitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Agitator')),
            ],
        ),
        migrations.AlterModelOptions(
            name='agitationevent',
            options={'ordering': ['start_date', 'place_id']},
        ),
        migrations.AddField(
            model_name='agitationeventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.AgitationEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='agitationeventparticipant',
            unique_together=set([('agitator', 'event')]),
        ),
    ]
