# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agitationevent',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='agitationplace',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
