# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0002_auto_20170612_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('data', models.TextField(blank=True, max_length=64000, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_update_time'],
            },
        ),
    ]
