# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0003_agitatorinregion_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='registrations_chat_it',
            field=models.BigIntegerField(),
        ),
    ]
