# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0005_auto_20170623_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agitator',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='agitator',
            name='last_name',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
