# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0007_agitationeventparticipant_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationevent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
