# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0008_agitationevent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgitationPlaceHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_place', to='street_agitation_bot.AgitationPlace')),
                ('sub_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='street_agitation_bot.AgitationPlace')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agitationplacehierarchy',
            unique_together=set([('base_place', 'sub_place')]),
        ),
    ]
