# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0009_auto_20170702_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationplacehierarchy',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agitationplacehierarchy',
            name='base_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_base_place', to='street_agitation_bot.AgitationPlace'),
        ),
        migrations.AlterField(
            model_name='agitationplacehierarchy',
            name='sub_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_sub_place', to='street_agitation_bot.AgitationPlace'),
        ),
    ]
