# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0011_agitationevent_agitators_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationevent',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agitationevent',
            name='agitators_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
