# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0012_auto_20170719_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='timezone_delta',
            field=models.IntegerField(default=0, help_text='Разница с UTC в секундах, например, для UTC+3 указано +10800'),
            preserve_default=False,
        ),
    ]
