# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0013_region_timezone_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationplace',
            name='post_apply_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
