# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0014_agitationplace_post_apply_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='registrations_chat_it',
            new_name='registrations_chat_id',
        ),
        migrations.AddField(
            model_name='agitationplace',
            name='registrations_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
