# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0015_auto_20170726_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgitationEventReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, help_text='Фактическое время начала', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Фактическое время окончания', null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgitationEventReportMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_count', models.PositiveIntegerField()),
                ('end_count', models.PositiveIntegerField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.AgitationEventReport')),
            ],
        ),
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CubeUsageInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Cube')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_delivered_by', to='street_agitation_bot.Agitator')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=1000)),
                ('private_name', models.CharField(max_length=1000)),
                ('geo_latitude', models.FloatField(blank=True, null=True)),
                ('geo_longitude', models.FloatField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Agitator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Region')),
            ],
        ),
        migrations.AddField(
            model_name='cubeusageinevent',
            name='delivered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_delivered_from', to='street_agitation_bot.Storage'),
        ),
        migrations.AddField(
            model_name='cubeusageinevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.AgitationEvent'),
        ),
        migrations.AddField(
            model_name='cubeusageinevent',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_shipped_by', to='street_agitation_bot.Agitator'),
        ),
        migrations.AddField(
            model_name='cubeusageinevent',
            name='shipped_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_shipped_to', to='street_agitation_bot.Storage'),
        ),
        migrations.AddField(
            model_name='cube',
            name='last_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Storage'),
        ),
        migrations.AddField(
            model_name='cube',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='cubeusageinevent',
            unique_together=set([('event',)]),
        ),
    ]
