# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_fake_agitator(apps, schema_editor):
    apps.get_model('street_agitation_bot', 'Agitator').objects.update_or_create(
        telegram_id=0,
        defaults=dict(first_name='NULL', last_name='NULL', phone='-'))


def set_fake_agitator(apps, schema_editor):
    fake = apps.get_model('street_agitation_bot', 'Agitator').objects.get(telegram_id=0)
    apps.get_model('street_agitation_bot', 'AgitationEvent').objects.update(master=fake)


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0016_auto_20170812_1409'),
    ]

    operations = [
        migrations.RunPython(create_fake_agitator, migrations.RunPython.noop),
        migrations.AddField(
            model_name='agitationevent',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Agitator'),
        ),
        migrations.RunPython(set_fake_agitator, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agitationevent',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Agitator'),
        ),
    ]
