# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0017_agitationevent_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationevent',
            name='need_cube',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
