# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0018_agitationevent_need_cube'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(max_length=200)),
                ('scheduled_moment', models.DateTimeField()),
                ('run_moment', models.DateTimeField()),
            ],
        ),
    ]
