# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 03:59
from __future__ import unicode_literals

from django.db import migrations

from street_agitation_bot import utils


def clean_phone_numbers(apps, schema_editor):
    for agitator in apps.get_model('street_agitation_bot', 'Agitator').objects.all():
        agitator.phone = utils.clean_phone_number(agitator.phone)
        agitator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0020_auto_20170812_2239'),
    ]

    operations = [
        migrations.RunPython(clean_phone_numbers, migrations.RunPython.noop),
    ]
