# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0022_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationevent',
            name='master2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AddField(
            model_name='agitationeventparticipant',
            name='agitator2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AddField(
            model_name='agitatorinregion',
            name='agitator2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AddField(
            model_name='storage',
            name='holder2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
    ]
