# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0024_auto_20170813_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agitationevent',
            name='master',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='holder',
        ),
        migrations.AlterUniqueTogether(
            name='agitationeventparticipant',
            unique_together=set([('agitator2', 'event')]),
        ),
        migrations.RemoveField(
            model_name='agitationeventparticipant',
            name='agitator',
        ),
        migrations.AlterUniqueTogether(
            name='agitatorinregion',
            unique_together=set([('agitator2', 'region')]),
        ),
        migrations.RemoveField(
            model_name='agitatorinregion',
            name='agitator',
        ),
    ]
