# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0025_auto_20170813_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agitationevent',
            old_name='master2',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='agitationeventparticipant',
            old_name='agitator2',
            new_name='agitator',
        ),
        migrations.RenameField(
            model_name='agitatorinregion',
            old_name='agitator2',
            new_name='agitator',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='holder2',
            new_name='holder',
        ),
        migrations.AlterUniqueTogether(
            name='agitationeventparticipant',
            unique_together=set([('agitator', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='agitatorinregion',
            unique_together=set([('agitator', 'region')]),
        ),
    ]
