# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0026_auto_20170813_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agitationevent',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AlterField(
            model_name='agitationeventparticipant',
            name='agitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AlterField(
            model_name='agitatorinregion',
            name='agitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User'),
        ),
    ]
