# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 07:52
from __future__ import unicode_literals

from django.db import migrations


def convert_agitator_to_user(apps, schema_editor):
    AgitatorModel = apps.get_model('street_agitation_bot', 'Agitator')
    UserModel = apps.get_model('street_agitation_bot', 'User')
    user_by_telegram_id = dict()
    for agitator in AgitatorModel.objects.all():
        user_by_telegram_id[agitator.telegram_id] = UserModel.objects.filter(telegram_id=agitator.telegram_id).first()
    for x in apps.get_model('street_agitation_bot', 'ConversationState').objects.all():
        if x.agitator_id:
            x.agitator2_id = user_by_telegram_id[x.agitator_id].id
            x.save()
    for x in apps.get_model('street_agitation_bot', 'CubeUsageInEvent').objects.all():
        if x.delivered_by:
            x.delivered_by2_id = user_by_telegram_id[x.delivered_by_id].id
            x.save()
        if x.shipped_by:
            x.shipped_by2_id = user_by_telegram_id[x.shipped_by_id].id
            x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0028_auto_20170813_0752'),
    ]

    operations = [
        migrations.RunPython(convert_agitator_to_user, migrations.RunPython.noop),
    ]
