# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0030_auto_20170813_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationstate',
            old_name='agitator2',
            new_name='agitator',
        ),
        migrations.RenameField(
            model_name='cubeusageinevent',
            old_name='delivered_by2',
            new_name='delivered_by',
        ),
        migrations.RenameField(
            model_name='cubeusageinevent',
            old_name='shipped_by2',
            new_name='shipped_by',
        ),
    ]
