# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0031_auto_20170813_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubeusageinevent',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_delivered_by', to='street_agitation_bot.User'),
        ),
        migrations.AlterField(
            model_name='cubeusageinevent',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_shipped_by', to='street_agitation_bot.User'),
        ),
    ]
