# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0034_auto_20170813_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubeusageinevent',
            name='transferred_to_storage',
            field=models.BooleanField(default=False),
        ),
    ]
