# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0035_cubeusageinevent_transferred_to_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_agitation_bot.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='adminrights',
            unique_together=set([('user', 'region')]),
        ),
    ]
