# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 10:42
from __future__ import unicode_literals

from django.db import migrations


def generate_admin_rights(apps, schema_editor):
    AgitatorInRegionModel = apps.get_model('street_agitation_bot', 'AgitatorInRegion')
    AdminRightsModel = apps.get_model('street_agitation_bot', 'AdminRights')

    for a in AgitatorInRegionModel.objects.filter(is_admin=True).all():
        AdminRightsModel.objects.create(user=a.agitator,
                                        region=a.region)

class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0036_auto_20170813_1042'),
    ]

    operations = [
           migrations.RunPython(generate_admin_rights, migrations.RunPython.noop)
    ]
