# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0038_remove_agitatorinregion_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='-', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='registrations_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
