# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_agitation_bot', '0040_auto_20170819_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrights',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
